In [2]:
import numpy as np

### Array Creation

There are 6 general mechanisms for creating arrays :
1. Conversion from other python structures (i.e lists and tuples)
2. Intrinsic Numpy array creation functions e.g arange, ones, zeros ..
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. creatings arrays from raw bytes through the use of strings or buffers
6. Use of special library functions e.g random


#### 1. Coonverting Python sequences to Numpy Arrays

Lists and tuples can define ndarray creation:
<font color=green>
>> - a list of numbers will create a 1D array
>> - a list of lists will create a 2D array
>> - further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.</font>



In [3]:
a1D = np.array([1,2,3,4])
a2D = np.array([[1,2],[3,4]])
a3D  = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [6]:
print(f"{a1D}\n\n{a2D}\n\n{a3D}")

[1 2 3 4]

[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### 2. Intrinsic np Array Creation Functions

NumPy has over 40 built-in functions for creating arrays as laid out in the Array creation routines<https://numpy.org/doc/1.26/reference/routines.array-creation.html#routines-array-creation>. These functions can be split into roughly three categories, based on the dimension of the array they create:

1. 1D arrays
Examples:
  -np.arange()
  -numpy.linspace > it will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 

In [4]:
import numpy as np

# arange
_1D_arange1 = np.arange(12)
print(_1D_arange1)

_1D_arange2 = np.arange(3, 13, dtype=float)
print(_1D_arange2)

_1D_arange3 = np.arange(2, 20, 0.5, dtype=float)
print(_1D_arange3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5
 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [5]:
# np.linespace
_1D_linspace1 = np.linspace(10, 20, 5)
print(_1D_linspace1)

[10.  12.5 15.  17.5 20. ]


2. 2D arrays
Examples:   
    -np.eye - defines a 2d identity matrix   
    -numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements.


In [6]:
# np.eye
_2D_eye1 = np.eye(3)
print(_2D_eye1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Diagram
_2D_diag1 = np.diag([1,2,3,4],2)
print(_2D_diag1)

[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


3. ndarrays

Examples:   
     np.ones  
     np.zeros   
     np.random  
    


In [12]:
import numpy as np
np.zeros((2,4))
np.ones((2,4))



from numpy.random import default_rng
default_rng(42).random(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 3. Replicating, Joining, or mutating existing arrays
> ->Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays.   
>  ->When you assign an array or its elements to a new variable, you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array.

In [4]:
# copy()
import numpy as np
copy_array = np.arange(1,10)
copy_array2 = copy_array[:4]
copy_array2 += 1

print( f'Copy1 {copy_array}\nCopy2 {copy_array2}')

Copy1 [2 3 4 5 5 6 7 8 9]
Copy2 [2 3 4 5]


In [5]:
copy_array = np.arange(1,10)
copy_array2 = copy_array[:4].copy()
copy_array2 += 1

print( f'Copy1 {copy_array}\nCopy2 {copy_array2}')

Copy1 [1 2 3 4 5 6 7 8 9]
Copy2 [2 3 4 5]


##### Joining
There are a number of ways of joining existing arrays:   
   -> np.vstack - this stacks arrays in sequence vertically (row wise)
   -> np.hstack - this stacks arrays in sequence Horizontally (column wise)    
   -> np.block  - Assemble an nd-array from nested lists of blocks.

In [13]:
A = np.ones((2,2)) 
B = np.eye(2,2)
C = np.zeros((2,2))
D = np.diag((-3,-4))

np.block([[A,B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [12]:
np.vstack((A, B))

np.hstack((A, B, C))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0., 0.]])

### Basic indexing

##### Single Element Indexing

>> Single element indexing works exactly like that for other standard Python sequences. It is 0-based, and accepts negative indices for indexing from the end of the array.   



In [15]:
a = np.arange(10)
a[2]
a[-2]

8

In [21]:
a.shape = (2,5)
print(f'{a}\n{a[1,3]}')

a[1,-1]

a[0][2]

[[0 1 2 3 4]
 [5 6 7 8 9]]
8


2

In [28]:
a.sum(1)

array([10, 35])

In [3]:
capitals = {'A': 1,
            'B': 2}

capitals['C'] = 3
capitals

{'A': 1, 'B': 2, 'C': 3}

In [4]:
my_string = "I'm ready"
my_string[4:8]

'read'

##### Slicing and Striding